# Generated by Django 5.1.3 on 2024-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='rejected_ballots',
            field=models.IntegerField(default=0),
        ),
    ]
